name: mylaundry
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  build_runner: ^2.4.15
  d_method: ^0.2.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.1.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
